language: android
jdk:
- oraclejdk8
android:
  components:
  - tools
  - platform-tools
  - build-tools-24.0.2
  - android-23
  - android-24
  - extra-android-support
  - extra-android-m2repository
  - extra-google-m2repository
script:
- "./gradlew build"
deploy:
  provider: releases
  api_key:
    secure: WdRrNvuec+jBj6emozGmRUnscHQlfObNNw0OGY4LK6/YJ06+Qnk3uEntDkEPP1lmLl5X/xfNQpo5YflpSHnEGgZL5R7lsZg6SNdPJokALySvQOil/YnSU5To/Grp86+g6KZtFtw83x03VN03s+N6eqRI/8Iy2yfQQLtt9sbbpjNkKAM+Q3uxRklOAKnkoz7cLHdihRuGybcKD9iTldy0g24rleskGhh8bun+LQiSQkvfm7cjPMi0xERiyae5mUqAdgUVmk7xgJFSmYMqCuYaoOMj1n5DTjaohan5DhknLEBrFoD3XSB7CPJM3vNBHG4yyXbFGjO7Ry/Wg54p8mkNYMywK8LxiF6NO02RZ2I0u+rT0mJ3MK1SxXFL9hKvnxdzRNymboLvd+bkqLW7xNvdmUC8X026GNArJId5aJP6rlToZyuKGjlM0cZp6eNSIFK1Z9a3QCvLqUt4jBl9Dfjn4EkXaQ0oje9vcxUcjHFBtIL4j9lBynIXZeqmO5xavu0Drg2xo+oU7zsoKZOY2o0vIJBOCIHfxJtuku9J0ZlvxKS7ZOqLxe5wDEe/SsBhgLk8ABlljP1BnOuO8bmzogc5EY3nxyAjhwyCkSzbGXm3rEOCHiW+xCEzDkQu4I9CWq6k3u36DKjuUQw8cA0XwF7lz4/oJoNYow+A9+bse4gWDws=
  file: app/build/outputs/apk/app-release-unsigned.apk
  skip_cleanup: true
  on:
    repo: Ezalor/MusicUU
    tags: ture
    all_branches: true
before_install:
- gem install fir-cli
after_deploy:
- fir p app/build/outputs/apk/app-release-unsigned.apk -T $FIR_TOKEN

